### PR TITLE
All-round CMake 3.1 and C++ 11 version compat fixes

### LINKED ISSUE #283: CMake version compatibility
With release version 2.2 we might review the minimum required CMake version.
It sounds reasonable that a bare install of the HighFive headers doesn't require more than CMake 3.0, but for complete Target export we require a relatively newer version, e.g. 3.5 already avail in Ubuntu LTS 16.
A deprecation message should be issued when using CMake 3.0.

### LINKED ISSUE #302: Eigen integration
Hi,
I am currently trying HighFive, in order to use it, concurrently with Eigen, in my project (FRyDoM : https://frydom.org/). The code is open-source but you need to register to access the repo (no need to for this issue).

I am having some difficulties using HighFive with Eigen. I created a dummy project, with the following CMakeLists

```cmake
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(foo)
set(CMAKE_CXX_STANDARD 14)
include(FetchContent)
FetchContent_Declare(highfive
            GIT_REPOSITORY https://github.com/BlueBrain/HighFive.git
            GIT_TAG master
            )
FetchContent_GetProperties(highfive)
FetchContent_Populate(highfive)
set(HIGHFIVE_USE_EIGEN ON CACHE BOOL "" FORCE)
add_subdirectory(${highfive_SOURCE_DIR} ${highfive_BINARY_DIR})
find_package(PkgConfig)
pkg_check_modules(EIGEN3 REQUIRED eigen3)
include_directories(SYSTEM ${EIGEN3_INCLUDE_DIRS})
add_executable(example_Eigen example_Eigen.cpp)
target_link_libraries(example_Eigen HighFive)
```
and example_Eigen.cpp contains

```c++
#include <iostream>
#include <highfive/H5Easy.hpp>
#include <Eigen/Eigen>

int main()
{
  {
    Eigen::MatrixXd D = Eigen::MatrixXd::Random(10,5);
    H5Easy::File file("example.h5", H5Easy::File::Overwrite);

    H5Easy::dump(file, "/path/to/D", D);

    auto a = H5Easy::load<Eigen::MatrixXd>(file, "/path/to/D");
    std::cout << a << std::endl;
  }
  return 0;
}
```
I got a compile error
```
[ 50%] Building CXX object CMakeFiles/example_Eigen.dir/example_Eigen.cpp.o
In file included from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5DataSpace.hpp:158,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5Attribute.hpp:14,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5File.hpp:75,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5Easy.hpp:38,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/example_Eigen.cpp:2:
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/H5Dataspace_misc.hpp: In instantiation of ‘static HighFive::DataSpace HighFive::DataSpace::From(const ScalarValue&) [with ScalarValue = Eigen::Matrix<double, -1, -1>]’:
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/h5easy_bits/H5Easy_scalar.hpp:28:70:   required from ‘static HighFive::DataSet H5Easy::detail::scalar::dump_impl<T, E>::run(HighFive::File&, const string&, const T&) [with T = Eigen::Matrix<double, -1, -1>; E = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/h5easy_bits/H5Easy_scalar.hpp:137:49:   required from ‘HighFive::DataSet H5Easy::dump(HighFive::File&, const string&, const T&, H5Easy::DumpMode) [with T = Eigen::Matrix<double, -1, -1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/lletourn/Documents/DEV/Test/test_HighFive/example_Eigen.cpp:11:39:   required from here
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/H5Dataspace_misc.hpp:136:43: error: static assertion failed: Only the following types are supported by DataSpace::From: 
  signed_arithmetic_types = int | long | float | double 
  unsigned_arithmetic_types = unsigned signed_arithmetic_types 
  string_types = std::string 
  all_basic_types = string_types | unsigned_arithmetic_types | signed_arithmetic_types 
   stl_container_types = std::vector<all_basic_types>   boost_container_types = boost::numeric::ublas::matrix<all_basic_types> | boost::multi_array<all_basic_types> 
  all_supported_types = all_basic_types | stl_container_types | boost_container_types  eigen_matrix_type = Eigen::Matrix<signed_arithmetic_type> | Eigen::VectorXX
         (std::is_arithmetic<ScalarValue>::value ||
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          std::is_enum<ScalarValue>::value ||
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
          std::is_same<std::string, ScalarValue>::value),
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/H5Attribute_misc.hpp:25,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5Attribute.hpp:75,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5File.hpp:75,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/H5Easy.hpp:38,
                 from /home/lletourn/Documents/DEV/Test/test_HighFive/example_Eigen.cpp:2:
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/H5Converter_misc.hpp: In instantiation of ‘HighFive::details::data_converter<Scalar, Enable>::data_converter(const Scalar&, const HighFive::DataSpace&) [with Scalar = Eigen::Matrix<double, -1, -1>; Enable = void]’:
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/../bits/H5Slice_traits_misc.hpp:238:44:   required from ‘void HighFive::SliceTraits< <template-parameter-1-1> >::write(const T&) [with T = Eigen::Matrix<double, -1, -1>; Derivate = HighFive::DataSet]’
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/h5easy_bits/H5Easy_scalar.hpp:29:9:   required from ‘static HighFive::DataSet H5Easy::detail::scalar::dump_impl<T, E>::run(HighFive::File&, const string&, const T&) [with T = Eigen::Matrix<double, -1, -1>; E = void; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/h5easy_bits/H5Easy_scalar.hpp:137:49:   required from ‘HighFive::DataSet H5Easy::dump(HighFive::File&, const string&, const T&, H5Easy::DumpMode) [with T = Eigen::Matrix<double, -1, -1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/lletourn/Documents/DEV/Test/test_HighFive/example_Eigen.cpp:11:39:   required from here
/home/lletourn/Documents/DEV/Test/test_HighFive/cmake-build-debug/_deps/highfive-src/include/highfive/bits/H5Converter_misc.hpp:121:52: error: static assertion failed: supported datatype should be an arithmetic value, a std::string or a container/array
         static_assert((std::is_arithmetic<Scalar>::value ||
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        std::is_enum<Scalar>::value ||
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
                        std::is_same<std::string, Scalar>::value),
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/example_Eigen.dir/build.make:62: recipe for target 'CMakeFiles/example_Eigen.dir/example_Eigen.cpp.o' failed
make[3]: *** [CMakeFiles/example_Eigen.dir/example_Eigen.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/example_Eigen.dir/all' failed
make[2]: *** [CMakeFiles/example_Eigen.dir/all] Error 2
CMakeFiles/Makefile2:84: recipe for target 'CMakeFiles/example_Eigen.dir/rule' failed
make[1]: *** [CMakeFiles/example_Eigen.dir/rule] Error 2
Makefile:164: recipe for target 'example_Eigen' failed
make: *** [example_Eigen] Error 2

```

However the easy_load_dump.cpp compiles and runs correctly. The D dataset with the Eigen matrix is in the example.h5. I had to specify set(CMAKE_CXX_STANDARD 14)  as in #269, though.

### PR DESCRIPTION
**Pull request by ferdonline**
Due to recent CMake versions in devel and travis CI, several compatibility issues were overlooked in recent updates, making HighFive only build well on recent Cmake (~3.11)
Further there was some code related to Eigen that required C++14.

## This PR
 - Revisits HighFive CMake commands and make everything compatible with CMake 3.1.
The reason for the version bump is regarding CXX_STANDARD. It has been long used in HighFive even though it was not available in CMake 3.0. This reassures us that almost no one is using Cmake 3.0 anymore (either way, after 4 years it sounds reasonable to bump the requirement from 3.0 to 3.1) and without CXX_STANDARD, requesting C++11 or 14 has to be done with native compiler commands.
- Adds integration tests with a sample project depending on HighFive, which are built in different settings.
- Fixes HighFive for C++11 min requirement (no c++14)
- Brings Eigen and XTensor dependencies to dependent projects

## Implementation details
 - Modifying imported targets is not portable. We therefore had to build two targets which completely independent (`_libheaders` and `_libdeps`). They are then linked to a main HighFive target depending on the scenario:
    - local tests / highfive added as subdirectory / installed highfive should bring dependency info: Both `_libheaders` and `_libdeps` are linked to HighFive
    -  installed highfive should rebuild dependency info: `HighFiveDeps.Cmake` is called to create a local _libdeps (without namespace) which together with the imported HighFive_libheaders form the new complete HighFive target. 
 - `string(APPEND ` replaced with `string(CONCAT`
 - Some simplification: E.g. dropped `select_recent_cxx_standard_available ` since it didn't bring benefits compared to always setting CMAKE_CXX_STANDARD to the minimum required
 
Tested locally with CMake 3.1 and 3.13

Fixes #283 
probably Fixes #302

### CODE REVIEW

**Comment by ferdonline** [comment]
And with this change we just detected there's C++14 code in HighFive 😨 
```H5Dataspace_misc.hpp:206:70: error: 'auto' not allowed in lambda parameter
     [](size_t so_far, const auto& v) {
```

File: CMake/HighFiveTargetExport.cmake [hunk 1]
```diff
@@ -26,23 +31,18 @@ install(FILES
...
-        EXPORT HighFiveTargets
-        INCLUDES DESTINATION include)
+# Specify targets to include in the HighFive Exports
+install(TARGETS _libheaders _libdeps
+        EXPORT HighFiveTargets)
 
 # Generate & install the Export for the INSTALL_INTERFACE
 install(EXPORT HighFiveTargets
-        FILE ${PROJECT_NAME}Targets.cmake
+        NAMESPACE HighFive
```
Comment (ferdonline) [inline CMake/HighFiveTargetExport.cmake]: By using a namespace exported targets are prefixed. That enables using the same `HighFiveTargetDeps.cmake` to build another deps target without risk of redefinition

File: doc/CMakeLists.txt [hunk 2]
```diff
@@ -3,5 +3,5 @@ if(Doxygen_FOUND)
     configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
     add_custom_target(doc COMMAND Doxygen::doxygen ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile)
 else()
-    message(WARNING "Doxygen documentation will not be built because Doxygen has not been found.")
+    message(STATUS "  Documentation (doc) cannot be built since Doxygen is not available.")
```
[the remark this answers is not in the document]
Comment (ferdonline) [reply doc/CMakeLists.txt]: Actually the target is not built automatically (is not added to ALL) so to build it one must call `make doc`. So IMHO the previous comment is more accurate.

[the remark this answers is not in the document]
Comment (alkino) [reply doc/CMakeLists.txt]: ok

File: include/highfive/h5easy_bits/H5Easy_Eigen.hpp [hunk 3]
```diff
@@ -23,41 +23,36 @@ namespace eigen {
...
+    if (std::decay<T>::type::ColsAtCompileTime == 1) {
         return {static_cast<size_t>(data.rows())};
     }
-
     return {static_cast<size_t>(data.rows()),
             static_cast<size_t>(data.cols())};
 }
 
+
+using EigenIndex = Eigen::DenseIndex;
```
Comment (tdegeus) [inline include/highfive/h5easy_bits/H5Easy_Eigen.hpp]: Just out of curiosity: what is the difference between `Eigen::Index` and `Eigen::DenseIndex`?

File: include/highfive/h5easy_bits/H5Easy_Eigen.hpp [hunk 4]
```diff
@@ -23,41 +23,36 @@ namespace eigen {
...
-        return std::vector<Eigen::Index>{static_cast<Eigen::Index>(dims[0]),
-                                         1u};
+        return std::vector<EigenIndex>{static_cast<EigenIndex>(dims[0]), 1u};
     }
-
     if (dims.size() == 2) {
-        return std::vector<Eigen::Index>{static_cast<Eigen::Index>(dims[0]),
-                                         static_cast<Eigen::Index>(dims[1])};
+        return std::vector<EigenIndex>{static_cast<EigenIndex>(dims[0]),
+                                         static_cast<EigenIndex>(dims[1])};
```
Comment (tdegeus) [inline include/highfive/h5easy_bits/H5Easy_Eigen.hpp]: Align for improved readability.

File: include/highfive/h5easy_bits/H5Easy_Eigen.hpp [hunk 5]
```diff
@@ -66,16 +61,15 @@ inline std::vector<Eigen::Index> shape(const File& file,
...
-            typename std::decay_t<T>::Scalar,
-            std::decay_t<T>::RowsAtCompileTime,
-            std::decay_t<T>::ColsAtCompileTime,
-            std::decay_t<T>::ColsAtCompileTime==1?Eigen::ColMajor:Eigen::RowMajor,
-            std::decay_t<T>::MaxRowsAtCompileTime,
-            std::decay_t<T>::MaxColsAtCompileTime>,
+            typename std::decay<T>::type::Scalar,
+            std::decay<T>::type::RowsAtCompileTime,
+            std::decay<T>::type::ColsAtCompileTime,
+            std::decay<T>::type::ColsAtCompileTime==1? Eigen::ColMajor : Eigen::RowMajor,
```
Comment (tdegeus) [inline include/highfive/h5easy_bits/H5Easy_Eigen.hpp]: It might be consistent to put a space before `?`

File: CMake/HighFiveConfig.cmake.in [hunk 6]
```diff
@@ -1,16 +1,42 @@
...
 # If the user sets this flag, all dependencies are preserved.
 # Useful in central deployments where dependencies are not prepared later
 option(HIGHFIVE_USE_INSTALL_DEPS "Use original Highfive dependencies" @HIGHFIVE_USE_INSTALL_DEPS@)
 if(HIGHFIVE_USE_INSTALL_DEPS)
+  # If enabled in the deploy config, request c++14
+  if(@HIGHFIVE_USE_XTENSOR@ AND NOT CMAKE_VERSION VERSION_LESS 3.8)
+    target_compile_features(HighFive INTERFACE cxx_std_14)
+  endif()
+  message("HIGHFIVE @PROJECT_VERSION@: Using original dependencies (HIGHFIVE_USE_INSTALL_DEPS=YES)")
+  target_link_libraries(HighFive INTERFACE HighFive_libheaders HighFive_libdeps)
```
Comment (tdegeus) [inline CMake/HighFiveConfig.cmake.in]: It could be elegant to have a few targets. E.g.:

* `HighFive`: bundles default.
* `HighFive_header`: HighFive's include path and C++ version.
* `HighFive_HDF5`: All HDF5 settings.
* `HighFive_HDF5_MPI`: All HDF5 settings with MPI enabled.
* `HighFive_Boost`: Enable Boost, and set include path.
* `HighFive_Eigen`: Enable Eigen, and set include path.
* `HighFive_xtensor`: Enable xtensor, and set include path.

Then the user can mix and match all it wants, if it does not want the default.

File: CMake/HighFiveTargetExport.cmake (hunk 1 above)
Comment (tdegeus) [reply CMake/HighFiveTargetExport.cmake]: Nice!

File: include/highfive/h5easy_bits/H5Easy_Eigen.hpp (hunk 3 above)
Comment (ferdonline) [reply include/highfive/h5easy_bits/H5Easy_Eigen.hpp]: Index is apparently generic, but became public API only in 3.3. From my understanding there are indexes for Sparse Matrixes.

File: CMake/HighFiveConfig.cmake.in (hunk 6 above)
Comment (ferdonline) [reply CMake/HighFiveConfig.cmake.in]: Now when the user doesnt want the deployed dependencies (default) he's given options to enable/disable Boost, Eigen and xtensor individually. The selected packages then become part of the HighFive interface. I find this to be sufficiently flexible.
Your suggestion is a different alternative; maybe I'm biased since I implemented this solution, but my feeling is that HighFive shouldn't be advertising third party targets, I honestly haven't seen any project doing it, and even though I guess you don't mean to export the original targets, it might be misleading/confusing to the user.
